variable "access_key" {}
variable "secret_key" {}
variable "region" {}
# CPU UTILIZATION
variable "prod_cpu_alarms_warning" {} 
variable "prod_cpu_alarms_high" {}
# MEMORY USAGE
variable "prod_memory_alarms_warning" {}
variable "prod_memory_alarms_high" {}
# DISK UTILIZATION
variable "prod_disk_root_alarms_warning" {}
variable "prod_disk_root_alarms_high" {}
variable "prod_disk_opt_alarms_warning" {}
variable "prod_disk_opt_alarms_high" {}
variable "prod_disk_var_alarms_warning" {}
variable "prod_disk_var_alarms_high" {}
# ELB Target Health Status
variable "prod_elb_tght_sh" {}
variable "prod_elb_tght_cribl" {}
variable "prod_elb_tght_cribl_internal" {}
# ELB Target Response time
variable "prod_elb_trt_sh" {}
variable "prod_elb_trt_cribl" {}
variable "prod_elb_trt_cribl_internal" {}
# ELB Target-4XX
variable "prod_elb_target_4XX_sh" {}
variable "prod_elb_target_4XX_cribl" {}
variable "prod_elb_target_4XX_cribl_internal" {}
# ELB Target-5XX
variable "prod_elb_target_5XX_sh" {}
variable "prod_elb_target_5XX_cribl" {}
variable "prod_elb_target_5XX_cribl_internal" {}
# ELB ELB-4XX
variable "prod_elb_elb_4XX_sh" {}
variable "prod_elb_elb_4XX_cribl" {}
variable "prod_elb_elb_4XX_cribl_internal" {}
# ELB ELB-5XX
variable "prod_elb_elb_5XX_sh" {}
variable "prod_elb_elb_5XX_cribl" {}
variable "prod_elb_elb_5XX_cribl_internal" {}