apiVersion: v1
description: DAN HDFS Helm Chart for K8s deployments
name: docker-hdfs
version: 1
appVersion: 3.1.3
home: https://hadoop.apache.org/
sources:
- https://github.com/apache/hadoop
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
