apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-httpfs
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: httpfs
spec:
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: httpfs
  minAvailable: {{ .Values.httpFs.pdbMinAvailable }}
