apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-datanode
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: datanode
spec:
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: datanode
  minAvailable: {{ .Values.dataNode.pdbMinAvailable }}