{{- if eq .Values.jmxExporter.dataNode.jmx_disable false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "config-volume-fullname" . }}-datanode-jmx-exporter
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    helm.sh/chart: {{ include "hadoop.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  jmx_exporter_config.yaml: |
    startDelaySeconds: {{ .Values.jmxExporter.dataNode.env.START_DELAY_SECONDS }}
    hostPort: {{ .Values.jmxExporter.dataNode.env.HOSTPORT }}
    username: {{ .Values.jmxExporter.dataNode.env.USERNAME }}
    password: {{ .Values.jmxExporter.dataNode.env.PASSWORD }}
    ssl: {{ .Values.jmxExporter.dataNode.env.SSL }}
    lowercaseOutputName: {{ .Values.jmxExporter.dataNode.env.LOWERCASE_OUTPUT_NAME }}
    lowercaseOutputLabelNames: {{ .Values.jmxExporter.dataNode.env.LOWERCASE_OUTPUT_LABEL_NAMES }}
    whitelistObjectNames: {{ .Values.jmxExporter.dataNode.env.WHITELIST_OBJECT_NAMES }}
    blacklistObjectNames: {{ .Values.jmxExporter.dataNode.env.BLACKLIST_OBJECT_NAMES }}
    {{- if .Values.jmxExporter.dataNode.env.RULES }}
    rules: {{ .Values.jmxExporter.dataNode.env.RULES }}
    {{- end }}
{{- end}}
