apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-datanode
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: datanode
spec:
  serviceName: {{ include "hadoop.fullname" . }}-datanode
  podManagementPolicy: Parallel
  replicas: {{ .Values.dataNode.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: datanode
  template:
    metadata:
      labels:
        app: {{ template "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: datanode
      annotations:
    {{- if eq .Values.jmxExporter.dataNode.jmx_disable false }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.jmxExporter.Port }}"
    {{- end}}
    spec:
      subdomain: {{ include "hadoop.fullname" . }}-datanode
      {{- if eq .Values.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ template "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: datanode
      {{- else if eq .Values.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ template "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: datanode
      {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
        - name: datanode
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - "/bin/bash"
            - "/tmp/hadoop-config/bootstrap.sh"
            - "-d"
          ports:
          - name: http
            containerPort: 9864
          - name: https
            containerPort: 9865
          - name: datanode
            containerPort: 9866
          - name: ipc
            containerPort: 9867
          livenessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 600
              periodSeconds: 5
              timeoutSeconds: 3
          resources:
{{ toYaml .Values.dataNode.resources | indent 12 }}
          env:
          - name: RANGER_ENABLED
            value: "{{ .Values.Ranger.Enabled }}"
          - name: MULTIHOMED_NETWORK
            value: "0"
          - name: DATANODE_JMX_DISABLE
            value: {{ .Values.jmxExporter.dataNode.jmx_disable | quote }}
          volumeMounts:
          - name: ranger-plugin-vol
            mountPath: /usr/local/ranger-hdfs-plugin/install.properties
            subPath: install.properties
          - name: hadoop-config
            mountPath: /tmp/hadoop-config
          - name: dfs
            mountPath: /usr/local/hadoop/hdfs
      {{- if eq .Values.jmxExporter.dataNode.jmx_disable false }}
        - image: "{{ .Values.jmxExporter.image.repository }}:{{ .Values.jmxExporter.image.tag }}"
          imagePullPolicy: {{ .Values.jmxExporter.imagePullPolicy }}
          name: jmx-exporter
          ports:
          - containerPort: {{ .Values.jmxExporter.Port }}
            name: jmx-metrics
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/jmx_exporter/config.yml
            name: jmx-exporter-configmap-volume
            subPath: config.yml
      {{- end}}
      volumes:
      - name: ranger-plugin-vol
        configMap:
          name: {{ template "config-volume-fullname" . }}-ranger-plugin
      - name: hadoop-config
        configMap:
          name: {{ template "config-volume-fullname" . }}-hadoop
    {{- if eq .Values.jmxExporter.dataNode.jmx_disable false }}
      - configMap:
          items:
          - key: jmx_exporter_config.yaml
            path: config.yml
          name: {{ template "config-volume-fullname" . }}-datanode-jmx-exporter
        name: jmx-exporter-configmap-volume
    {{- end}}
      {{- if .Values.persistence.dataNode.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: dfs
      spec:
        accessModes: [{{ .Values.persistence.dataNode.accessMode | quote }}]
        storageClassName: {{ .Values.persistence.dataNode.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.dataNode.size | quote }}
      {{- else }}
      - name: dfs
        emptyDir: {}
      {{- end }}
