apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-journalnode
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: journalnode
spec:
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: journalnode
  minAvailable: {{ .Values.journalNode.pdbMinAvailable }}
